import React from 'react';

const TermsOfServicePage: React.FC = () => {
  return (
    <div className="container mx-auto max-w-4xl py-8 px-4">
      <div className="bg-white p-8 md:p-12 rounded-2xl shadow-sm border border-slate-200/80 prose prose-slate">
        <h1 className="text-4xl font-bold tracking-tight text-slate-800">Terms of Service</h1>
        <p className="text-sm text-slate-500">Last updated: {new Date().toLocaleDateString()}</p>
        
        <p>
          Please read these Terms of Service ("Terms") carefully before using the AI Pinterest Pin Generator By youness azaguag (the "Application"). Your access to and use of the Application is conditioned on your acceptance of and compliance with these Terms.
        </p>
        
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using the Application, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Application.
        </p>
        
        <h2>2. Use of the Application</h2>
        <p>
          The Application is provided to help you create visual content for Pinterest and other platforms. You agree to use the Application in compliance with all applicable laws and regulations.
        </p>
        <ul>
          <li><strong>API Key:</strong> You are required to provide your own Google AI API Key to use certain features. You are solely responsible for all activities that occur under your API key.</li>
          <li><strong>Content Responsibility:</strong> You are solely responsible for the text prompts you provide and the images and text generated ("Content"). You agree not to create any Content that is illegal, offensive, or infringes on the rights of others.</li>
          <li><strong>Third-Party Policies:</strong> Your use of the generated Content must comply with the terms of service of any platform where you publish it, including but not to Pinterest's and Google's policies.</li>
        </ul>

        <h2>3. Intellectual Property</h2>
        <p>
          The Application and its original content (excluding Content generated by you) features and functionality are and will remain the exclusive property of the Application's creators. To the extent permitted by Google's terms, you own the Content you create.
        </p>

        <h2>4. Disclaimer of Warranty</h2>
        <p>
            The Application is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranty that the service will be uninterrupted, timely, secure, or error-free. The quality of generated content is dependent on the underlying AI models provided by Google, and we make no guarantees about its accuracy or suitability for any purpose.
        </p>

        <h2>5. Limitation of Liability</h2>
        <p>
            In no event shall the creators of the Application be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Application.
        </p>

        <h2>6. Changes to Terms</h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.
        </p>

        <h2>Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us.
        </p>
      </div>
    </div>
  );
};

export default TermsOfServicePage;